<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rs</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>Rust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block_doc_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_doc_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\{)</string>
			<key>name</key>
			<string>punctuation.section.scope.begin.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\})</string>
			<key>name</key>
			<string>punctuation.section.scope.end.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\!?\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute.begin.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attribute</string>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute.end.rust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.attribute.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_literal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.rust</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape.rust</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single-quote string (character literal)</string>
			<key>match</key>
			<string>(')([^'\\]|(\\(x\h{2}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)))(')</string>
			<key>name</key>
			<string>string.quoted.single.rust</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#raw_string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Floating point number (fraction)</string>
			<key>match</key>
			<string>\b[0-9][0-9_]*\.[0-9][0-9_]*([eE][+-][0-9_]+)?(f32|f64)?\b</string>
			<key>name</key>
			<string>constant.numeric.float.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Floating point number (exponent)</string>
			<key>match</key>
			<string>\b[0-9][0-9_]*(\.[0-9][0-9_]*)?[eE][+-][0-9_]+(f32|f64)?\b</string>
			<key>name</key>
			<string>constant.numeric.float.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Floating point number (typed)</string>
			<key>match</key>
			<string>\b[0-9][0-9_]*(\.[0-9][0-9_]*)?([eE][+-][0-9_]+)?(f32|f64)\b</string>
			<key>name</key>
			<string>constant.numeric.float.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integer number (decimal)</string>
			<key>match</key>
			<string>\b[0-9][0-9_]*([ui](8|16|32|64)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integer number (hexadecimal)</string>
			<key>match</key>
			<string>\b0x[a-fA-F0-9_]+([ui](8|16|32|64)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integer number (octal)</string>
			<key>match</key>
			<string>\b0o[0-7_]+([ui](8|16|32|64)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integer number (binary)</string>
			<key>match</key>
			<string>\b0b[01_]+([ui](8|16|32|64)?)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Static storage modifier</string>
			<key>match</key>
			<string>\bstatic\b</string>
			<key>name</key>
			<string>storage.modifier.static.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Visibility modifier</string>
			<key>match</key>
			<string>\b(priv|pub)\b</string>
			<key>name</key>
			<string>storage.modifier.visibility.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean constant</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control keyword</string>
			<key>match</key>
			<string>\b(break|continue|do|else|if|in|for|loop|match|return|while)\b</string>
			<key>name</key>
			<string>keyword.control.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>\b(crate|extern|mod|let|proc|ref|use)\b</string>
			<key>name</key>
			<string>keyword.other.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Unsafe code keyword</string>
			<key>match</key>
			<string>\bunsafe\b</string>
			<key>name</key>
			<string>keyword.other.unsafe.rust</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sigils</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#std_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#kinds</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#self</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mut</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#box</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lifetime</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ref_lifetime</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>(\+|-|/|\*|=|\^|&amp;|\||!|&gt;|&lt;|%|::|\bas\b)</string>
			<key>name</key>
			<string>keyword.operator.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Standard library macro</string>
			<key>match</key>
			<string>\b(log|error|warn|info|debug|log_enabled|fail|assert|assert_eq|unreachable|unimplemented|format|write|writeln|print|println|local_data_key|try|vec|select)!</string>
			<key>name</key>
			<string>support.function.std.rust</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Standard library type variant</string>
			<key>match</key>
			<string>\b(Some|None|Ok|Err)\b</string>
			<key>name</key>
			<string>support.constant.std.rust</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.macro.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Invocation of a macro</string>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*\!)\s*[({\[]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rust.call</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function call</string>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s*\(</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(fn)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.fn.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function definition</string>
			<key>end</key>
			<string>(?[\{;])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(enum|struct|trait|type)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Type declaration</string>
			<key>end</key>
			<string>(?[\{;])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(impl)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Implementation</string>
			<key>end</key>
			<string>(?\{)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>comment</key>
			<string>Variable declaration</string>
			<key>end</key>
			<string>[=;,\)\|]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.rust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_doc_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>block_doc_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*[!\*][^\*]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block documentation comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.rust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_doc_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>box</key>
		<dict>
			<key>comment</key>
			<string>Box storage modifier</string>
			<key>match</key>
			<string>\bbox\b</string>
			<key>name</key>
			<string>storage.modifier.box.rust</string>
		</dict>
		<key>escaped_character</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
			<key>name</key>
			<string>constant.character.escape.rust</string>
		</dict>
		<key>kinds</key>
		<dict>
			<key>comment</key>
			<string>Built-in trait (kind)</string>
			<key>match</key>
			<string>\b(Send|Sized|Copy|Share)\b</string>
			<key>name</key>
			<string>support.type.kind.rust</string>
		</dict>
		<key>lifetime</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.lifetime.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Named lifetime</string>
			<key>match</key>
			<string>'([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>storage.modifier.lifetime.rust</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.rust</string>
		</dict>
		<key>line_doc_comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single-line documentation comment</string>
			<key>match</key>
			<string>(//)[!/][^/].*$\n?</string>
			<key>name</key>
			<string>comment.line.documentation.rust</string>
		</dict>
		<key>mut</key>
		<dict>
			<key>comment</key>
			<string>Mutable storage modifier</string>
			<key>match</key>
			<string>\bmut\b</string>
			<key>name</key>
			<string>storage.modifier.mut.rust</string>
		</dict>
		<key>raw_string</key>
		<dict>
			<key>begin</key>
			<string>r#"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Raw string</string>
			<key>end</key>
			<string>"#</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.rust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.raw.rust</string>
		</dict>
		<key>ref_lifetime</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.lifetime.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.lifetime.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Reference with named lifetime</string>
			<key>match</key>
			<string>&amp;('([a-zA-Z_][a-zA-Z0-9_]*))\b</string>
		</dict>
		<key>self</key>
		<dict>
			<key>comment</key>
			<string>Self variable</string>
			<key>match</key>
			<string>\bself\b</string>
			<key>name</key>
			<string>variable.language.rust</string>
		</dict>
		<key>sigils</key>
		<dict>
			<key>comment</key>
			<string>Sigil</string>
			<key>match</key>
			<string>[&amp;~@*](?=[a-zA-Z0-9_\(\[\|\"]+)</string>
			<key>name</key>
			<string>keyword.operator.sigil.rust</string>
		</dict>
		<key>std_types</key>
		<dict>
			<key>comment</key>
			<string>Standard library type</string>
			<key>match</key>
			<string>\b(Box|Vec|StrBuf|Path|Option|Result|Reader|Writer|Stream|Seek|Buffer|IoError|IoResult|Sender|SyncSender|Receiver|Cell|RefCell|Any)\b</string>
			<key>name</key>
			<string>support.class.std.rust</string>
		</dict>
		<key>string_literal</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double-quote string</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.rust</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_character</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>comment</key>
			<string>Built-in type</string>
			<key>match</key>
			<string>\b(bool|char|usize|isize|u8|u16|u32|u64|i8|i16|i32|i64|f32|f64|str|Self)\b</string>
			<key>name</key>
			<string>storage.type.rust</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rust</string>
	<key>uuid</key>
	<string>E54FA931-0668-4496-8922-F91520AD02B3</string>
</dict>
</plist>