<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfn\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Rust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#rust_comment_doc_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rust_comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rust_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rust_raw_string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\b</string>
			<key>name</key>
			<string>storage.type.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b_*[A-Z][a-zA-Z0-9_]*[a-z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>storage.type.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(c_[a-z0-9_]+|[a-z_][a-z0-9_]*_t)\b</string>
			<key>name</key>
			<string>storage.type.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z_][A-Z0-9_]+)\b</string>
			<key>name</key>
			<string>constant.other.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'[a-zA-Z_][a-zA-Z0-9_]*(?!\')\b</string>
			<key>name</key>
			<string>storage.modifier.lifetime.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'(?=([^\'\\]|\\(x\h{2}|u\{\h{1,6}\}|n|r|t|0|"|'|\\))\')</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_escaped_character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.source.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(fn)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>meta.function.source.rust</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.source.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro.source.rust</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(macro_rules!)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>meta.macro.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(crate|enum|extern|fn|impl|let|mod|move|mut|pub|ref|static|struct|super|trait|type|unsafe|use|const|where)\b</string>
			<key>name</key>
			<string>keyword.other.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|else|for|if|loop|match|return|while|continue)\b</string>
			<key>name</key>
			<string>keyword.control.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|in|box)\b</string>
			<key>name</key>
			<string>keyword.operator.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(virtual|proc|alignof|become|offsetof|priv|pure|sizeof|typeof|unsized|yield|do|abstract|final|override|macro)\b</string>
			<key>name</key>
			<string>invalid.illegal.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self)\b</string>
			<key>name</key>
			<string>variable.language.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!::)\b(Self|i8|i16|i32|i64|isize|u8|u16|u32|u64|usize|f32|f64|bool|char|str)\b</string>
			<key>name</key>
			<string>storage.type.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#!?\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>comment.block.attribute.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rust_raw_string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9_]*(i8|i16|i32|i64|isize|u8|u16|u32|u64|usize)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0x[0-9a-fA-F_]*[0-9a-fA-F][0-9a-fA-F_]*(i8|i16|i32|i64|isize|u8|u16|u32|u64|usize)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0o[0-7_]*[0-7][0-7_]*(i8|i16|i32|i64|isize|u8|u16|u32|u64|usize)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0b[0-1_]*[0-1][0-1_]*(i8|i16|i32|i64|isize|u8|u16|u32|u64|usize)?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9_]*((f32|f64)|([eE][+-]?[0-9_]*[0-9][0-9_]*(f32|f64)?)|(\.([0-9][0-9_]*([eE][+-]?[0-9_]*[0-9][0-9_]*)?(f32|f64)?)?))\b</string>
			<key>name</key>
			<string>constant.numeric.float.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//[!/][^/].*</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.documentation.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-=&lt;&gt;&amp;|!~@.,;:?+*/%^'#$]|\b_\b</string>
			<key>name</key>
			<string>keyword.operator.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[(){}\[\]]|::</string>
			<key>name</key>
			<string>meta.default.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-z_][a-z0-9_]*(?=\()</string>
			<key>name</key>
			<string>support.function.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Copy|Send|Sized|Sync|Drop|Fn|FnMut|FnOnce|Box|ToOwned|Clone|PartialEq|PartialOrd|Eq|Ord|AsRef|AsMut|Into|From|Default|Iterator|Extend|IntoIterator|DoubleEndedIterator|ExactSizeIterator|Option|Some|None|Result|Ok|Err|SliceConcatExt|String|ToString|Vec)\b</string>
			<key>name</key>
			<string>support.type.source.rust</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>rust_comment_block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rust_comment_doc_block</string>
				</dict>
			</array>
		</dict>
		<key>rust_comment_doc_block</key>
		<dict>
			<key>begin</key>
			<string>/\*[!\*][^\*/]</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rust_comment_doc_block</string>
				</dict>
			</array>
		</dict>
		<key>rust_escaped_character</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|u\{\h{1,6}\}|n|r|t|0|"|'|\\)</string>
			<key>name</key>
			<string>constant.character.escape.source.rust</string>
		</dict>
		<key>rust_raw_string</key>
		<dict>
			<key>begin</key>
			<string>r(#*)"</string>
			<key>end</key>
			<string>"(\1)</string>
			<key>name</key>
			<string>string.quoted.double.raw.source.rust</string>
		</dict>
		<key>rust_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_escaped_character</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rust</string>
	<key>uuid</key>
	<string>4339386b-4d67-4f0e-9e78-09ecbcddf71d</string>
</dict>
</plist>
