#!/bin/sh
# ----------------------------------------------------------------------------
# Copyright (c) 2019 Fraunhofer FOKUS and others.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
# ----------------------------------------------------------------------------
# Update this script if a newer version of Maven or the wrapper shall be used.
# ----------------------------------------------------------------------------

mvn -U -N io.takari:maven:0.7.7:wrapper -Dmaven=3.6.3